### ISSUE TITLE
REAL contents of /efi is missing after completion of roll out.

### ISSUE THREAD

**Issue by connaisseur** [bgh-github/arch-uefi-cloudimg#1]
The whole undertaking of your script is neat. At least someone tries to come into the 2020ies with a Linux PVE cloudinit setup and UEFI.

Some issues I've noted so far. The script creates a EF00 partition and fills it.

Somewhere in your image the /efi directory is also poplated. The "bootctl" command shows the output correctly.

BUT per Arch installation wiki page Paragraph 3 "Installing the UEFI boot manager" talks about having /efi or /boot as **mount point**. This is missing.

I prefer to mix the EF00 partition and the /boot directory together. Create /boot, mount the EF00 partition . Populate everything with pacstrap and create with "genfstab -U /mnt >> /mnt/etc/fstab" a valid /etc/fstab

With the current state of the script updating system-boot / bootctl would become a nightmare. At least it will fail.

For my taste the loader entries should have the files for the standard boot and the fallback boot populated. Also valid minitcpio images would be good.

It's taste... and yes this involves heavily scripting.

But it's a challenge.

**Comment by bgh-github** [comment]
Appreciate you checking things out.

I should be upfront that the build leans more heavily into modern systemd feature set and conventions than the README currently lets on. A more recent update also switched to booting from UKI. These modern features provide some nice quality-of-life improvements which help simplifying (or even eliminating) certain configuration.

Take the partitions; the type codes specified on creation map to the respective types set out in [discoverable partition specification](https://uapi-group.org/specifications/specs/discoverable_partitions_specification/). For the running image, this allows for automatic discovery and mounting, no fstab required!

Several systems I maintain based on the image seem fine updating systemd-boot components. The updates automated by taking advantage of [systemd-boot-update.service](https://wiki.archlinux.org/title/Systemd-boot#systemd_service).

It's a similar situation with the boot loader. systemd-boot should [automatically locate](https://wiki.archlinux.org/title/Unified_kernel_image#systemd-boot) UKIs (one main, one fallback created per mkinitcpio preset config) in ESP.

Had you encountered problems utilising the image, or thus far just noting potential issues from reviewing the build script?

**Comment by connaisseur** [comment]
I beg you pardon, that I'm not so up to date with recent development around system / UKI and discoverable partition table specifications.

Up to now, I've set UEFI booting old school style with EFI dir inside /boot. Maybe things should change.

The image instantly worked out fine with my Proxmox installaion + the proper YAML config file for cloud-init. No issues so far.

Thanks for compiling it and the heads up on recent developments.

Feel free to close this PR.

**Comment by bgh-github** [comment]
No problem. Learning about and working out where new developments can be integrated is all part of it.

Glad to hear the image worked out of the box in your Proxmox environment.
